# Generated by Django 5.1.3 on 2024-12-02 17:53

import service.service
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='название')),
                ('image', models.ImageField(upload_to=service.service.loading_category_images, verbose_name='изображение')),
                ('slug', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Категории интересов',
                'verbose_name_plural': 'Категории интересов',
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField(verbose_name='id пользов. аккаунта')),
                ('is_bot', models.BooleanField(default=False, verbose_name='бот')),
                ('first_name', models.CharField(max_length=100, verbose_name='имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='фамилия')),
                ('username', models.CharField(max_length=100, verbose_name='username')),
            ],
            options={
                'verbose_name': 'Пользоват. телеграмма',
                'verbose_name_plural': 'Пользоват. телеграмма',
            },
        ),
    ]
