# Generated by Django 5.1.3 on 2024-12-03 13:11

import django.core.validators
import django.db.models.deletion
import service.service
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='название')),
                ('slug', models.CharField(max_length=100)),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='дата создания')),
            ],
            options={
                'verbose_name': 'Категорию интереса',
                'verbose_name_plural': 'Категории интересов',
            },
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='город')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('slug', models.CharField(max_length=75)),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.CharField(max_length=12, unique=True, verbose_name='id пользов. аккаунта телеграмма')),
                ('is_bot', models.BooleanField(default=False, verbose_name='бот')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='имя')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='фамилия')),
                ('username', models.CharField(max_length=100, verbose_name='username')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='дата создания')),
            ],
            options={
                'verbose_name': 'Пользователя телеграмма',
                'verbose_name_plural': 'Пользователи телеграмма',
            },
        ),
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='название')),
                ('image', models.ImageField(upload_to=service.service.loading_interests_images, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])], verbose_name='изображение')),
                ('slug', models.CharField(max_length=100)),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests_categories', to='users.categories', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Интерес',
                'verbose_name_plural': 'Интересы',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, help_text='расскажи о себе', max_length=300, null=True, verbose_name='описание')),
                ('films', models.CharField(blank=True, max_length=50, null=True, verbose_name='фильмы')),
                ('books', models.CharField(blank=True, max_length=50, null=True, verbose_name='книги')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_profiles', to='users.cities', verbose_name='город')),
                ('interests', models.ManyToManyField(blank=True, null=True, related_name='interest_profiles', to='users.interests', verbose_name='интересы')),
                ('user_teleg', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_user_teleg', to='users.telegramuser', verbose_name='пользователь телеграм. аккаунта')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='ProfileImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=service.service.loading_profile_images, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])], verbose_name='изображение')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_images', to='users.profile', verbose_name='профиль')),
            ],
            options={
                'verbose_name': 'Изображения профиля',
                'verbose_name_plural': 'Изображение профиля',
            },
        ),
    ]
