# Generated by Django 5.1.3 on 2024-12-03 16:11

import django.core.validators
import service.service
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], default='М', max_length=3),
        ),
        migrations.AlterField(
            model_name='interests',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=service.service.loading_interests_images, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])], verbose_name='изображение'),
        ),
    ]
