# Generated by Django 5.1.3 on 2024-12-02 18:27

import django.db.models.deletion
import service.service
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_categories_image_categories_create_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'verbose_name': 'Пользователи телеграмма', 'verbose_name_plural': 'Пользователи телеграмма'},
        ),
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='название')),
                ('image', models.ImageField(upload_to=service.service.loading_interests_images, verbose_name='изображение')),
                ('slug', models.CharField(max_length=100)),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests_categories', to='users.categories', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Интерес',
                'verbose_name_plural': 'Интересы',
            },
        ),
    ]
