# Generated by Django 5.1.3 on 2024-12-03 06:26

import django.core.validators
import service.service
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_telegramuser_options_interests'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='город')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('slug', models.CharField(max_length=75)),
            ],
            options={
                'verbose_name': 'Города',
                'verbose_name_plural': 'Город',
            },
        ),
        migrations.AlterField(
            model_name='interests',
            name='image',
            field=models.ImageField(upload_to=service.service.loading_interests_images, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])], verbose_name='изображение'),
        ),
    ]
