# Generated by Django 5.1.3 on 2024-12-03 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_cities_alter_interests_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='id_user',
            field=models.IntegerField(verbose_name='id пользов. аккаунта телеграмма'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='фамилия'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, help_text='расскажи о себе', max_length=300, null=True, verbose_name='описание')),
                ('films', models.CharField(blank=True, max_length=50, null=True, verbose_name='фильмы')),
                ('books', models.CharField(blank=True, max_length=50, null=True, verbose_name='книги')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_profiles', to='users.cities', verbose_name='город')),
                ('interests', models.ManyToManyField(blank=True, null=True, related_name='interest_profiles', to='users.interests', verbose_name='интересы')),
                ('user_teleg', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_user_teleg', to='users.telegramuser', verbose_name='пользователь телеграм. аккаунта')),
            ],
        ),
    ]
