# Generated by Django 5.1.3 on 2024-12-10 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('like_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_liked', to='users.profile', verbose_name='понравившийся пользователь')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_likes', to='users.profile', verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Нравиться',
                'verbose_name_plural': 'Нравиться',
            },
        ),
    ]
