# Generated by Django 5.1.3 on 2024-12-03 07:12

import django.core.validators
import django.db.models.deletion
import service.service
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_telegramuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Категорию интереса', 'verbose_name_plural': 'Категории интересов'},
        ),
        migrations.AlterModelOptions(
            name='cities',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'verbose_name': 'Пользователя телеграмма', 'verbose_name_plural': 'Пользователи телеграмма'},
        ),
        migrations.CreateModel(
            name='ProfileImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=service.service.loading_profile_images, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])], verbose_name='изображение')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_images', to='users.profile', verbose_name='профиль')),
            ],
            options={
                'verbose_name': 'Изображения профиля',
                'verbose_name_plural': 'Изображение профиля',
            },
        ),
    ]
