# Generated by Django 5.1.3 on 2024-12-10 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_likeuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likeuser',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='likeuser',
            name='user_teleg',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_likes', to='users.telegramuser', verbose_name='пользователь'),
            preserve_default=False,
        ),
    ]
