# Generated by Django 5.1.3 on 2024-12-11 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_likeuser_user_profile_likeuser_user_teleg'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='аватарка в телеграмме(url)'),
        ),
        migrations.AlterField(
            model_name='likeuser',
            name='like_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_likes', to='users.profile', verbose_name='понравившийся профиль пользователя'),
        ),
        migrations.AlterField(
            model_name='likeuser',
            name='user_teleg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_teleg_likes', to='users.telegramuser', verbose_name='пользователь'),
        ),
    ]
