# Generated by Django 5.1.3 on 2024-12-03 07:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_categories_options_alter_cities_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileimages',
            name='create_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='дата создания'),
            preserve_default=False,
        ),
    ]
