# Generated by Django 5.1.3 on 2024-12-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_telegramuser_image_alter_likeuser_like_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='возраст'),
        ),
    ]
