# Generated by Django 5.1.3 on 2024-12-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='image',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='аватарка в телеграмме(url)'),
        ),
    ]
